### ISSUE TITLE
Dont work in osX 

### ISSUE THREAD

**Issue by diegogonzalez** [unity/n1-avatars#6]
The plugin show succesfull install and it is enabled but avatars doesnt appear. What other info I can provide?

**Comment by diegogonzalez** [comment]
I could get the log error: 

```bash
package.coffee:170 ReferenceError: Unknown plugin "transform-async-generator-functions" specified in "base" at 0, attempted to resolve relative to "/Users/diego/.nylas-mail/packages/n1-avatars/lib"
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at OptionManager.mergeOptions (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.exports.compile (/Applications/Nylas Mail.app/Contents/Resources/app.asar/src/compile-support/babel.js:50:16)
    at compileFileAtPath (/Applications/Nylas Mail.app/Contents/Resources/app.asar/src/compile-cache.js:56:44)
    at Object.value [as .es6] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/src/compile-cache.js:146:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at require (internal/module.js:20:19)
    at Package.module.exports.Package.requireMainModule (/src/package.coffee:311:21)
    at Package.module.exports.Package.activateConfig (/src/package.coffee:178:6)
    at Package.module.exports.Package.activateNow (/src/package.coffee:162:8)
    at /src/package.coffee:156:10
    at Package.module.exports.Package.measure (/src/package.coffee:107:13)
    at Package.module.exports.Package.activate (/src/package.coffee:154:8)
    at PackageManager.module.exports.PackageManager.activatePackage (/src/package-manager.coffee:599:12)
    at /src/package-manager.coffee:460:10
    at /src/config.coffee:560:9
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/src/config.coffee:624:14)
    at Config.module.exports.Config.updateSettings (/src/config.coffee:539:6)
    at Config.updateSettings (/src/config.coffee:1:1)
    at EventEmitter.<anonymous> (/src/config.coffee:339:10)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

**Comment by bigmmind** [comment]
+1 Doesn't work on OS X Sierra

![screen shot 2017-02-15 at 12 28 19](https://cloud.githubusercontent.com/assets/23629885/22968142/4b51b7a0-f37a-11e6-83bb-8565e67431d4.png)


![screen shot 2017-02-15 at 12 14 07](https://cloud.githubusercontent.com/assets/23629885/22968061/0b754b9c-f37a-11e6-9c32-48c389ed6e20.png)
![screen shot 2017-02-15 at 12 14 18](https://cloud.githubusercontent.com/assets/23629885/22968062/0b76d818-f37a-11e6-94c6-8f53f270b65b.png)
![screen shot 2017-02-15 at 12 20 29](https://cloud.githubusercontent.com/assets/23629885/22968063/0b772084-f37a-11e6-9fee-936155ea80fb.png)

**Comment by behzadsh** [comment]
+1
Same here

**Comment by natecox** [comment]
I just installed this on macOS, on a fresh install of Nylas, with no issues.

**Comment by abogawat** [comment]
Works for me. Latest version of MacOS Sierra, fresh install of Nylas 2.
